[package]
name = "chess-website"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
chess = "3.2.0"
console_error_panic_hook = "0.1.7"
serde = "1.0.217"
wasm-bindgen = "0.2.99"
serde-wasm-bindgen = "0.6"
web-sys = { version = "0.3.76", features = ["console"] }
